server:
  port: 8383

spring:
  application:
    name: library_management_system

  datasource:
    url: jdbc:mysql://localhost:3306/library_management_system
    username: root
    password: 1234
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jakarta:
          persistence:
            sharedCache:
              mode: ENABLE_SELECTIVE